steps:
  # 1단계: 이미지를 빌드하고, 완성되면 창고에 확실하게 업로드(--publish) 합니다.
  # 태그를 latest 대신 고유한 커밋 번호($SHORT_SHA)로 지정합니다.
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'asia-northeast3-docker.pkg.dev/skilled-eon-352414/cloud-run-source-deploy/stylebot.chosun.com-v2:$SHORT_SHA'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--env=VITE_API_KEY=$_VITE_API_KEY'
      - '--publish'

  # 2단계: 고유한 이름표($SHORT_SHA)가 붙은 최신 이미지를 Cloud Run에 배포합니다.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'chosun-frontend-app'
      - '--image=asia-northeast3-docker.pkg.dev/skilled-eon-352414/cloud-run-source-deploy/stylebot.chosun.com-v2:$SHORT_SHA'
      - '--region=asia-northeast3'

options:
  logging: CLOUD_LOGGING_ONLY